services:
  db:
    image: postgres:16-alpine
    hostname: chatwork-post-db
    restart: always
    ports:
      - "6202:5432" # 単体起動時はホストPCから 6202 でアクセス可
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: chatwork-post
    hostname: chatwork-post-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "6201:6201"
    command: node ./dist-ssr/index.js
    environment:
      - VITE_BACKEND_URL=http://chatwork-post-backend
      - VITE_DB_URL=postgres://postgres:postgres@chatwork-post-db:5432/chatwork-post
    depends_on:
      - db
  frontend:
    image: chatwork-post
    restart: always
    ports:
      - "6200:6200"
    command: sh -c "cd ./dist && http-server -p 6200"
    environment:
      - VITE_BACKEND_URL=http://chatwork-post-backend
    depends_on:
      - backend
      - db
