services:
  db:
    image: postgres:16-alpine
    hostname: chatpost-db
    ports:
      - "7200:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-backend
  backend:
    image: chatpost
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3200:3200"
    command: node ./dist-ssr/index.js
    environment:
      - VITE_DB_URL=postgres://postgres:postgres@chatpost-db:5432/chatpost
    depends_on:
      - db
    networks:
      - db-backend
  frontend:
    image: chatpost
    ports:
      - "5200:5200"
    command: serve -s ./dist -p 5200
    depends_on:
      - backend
      - db
networks:
  db-backend:
    driver: bridge
