services:
  db:
    image: postgres:16-alpine
    hostname: chatpost-db
    ports:
      - "7200:5432" # 単体起動時はホストPCから7200でアクセス可
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: chatpost
    hostname: chatpost-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3200:3200"
    command: node ./dist-ssr/index.js
    environment:
      - VITE_BACKEND_URL=http://chatpost-backend
      - VITE_DB_URL=postgres://postgres:postgres@chatpost-db:5432/chatpost
    depends_on:
      - db
  frontend:
    image: chatpost
    ports:
      - "5200:5200"
    command: serve -s ./dist -p 5200
    environment:
      - VITE_BACKEND_URL=http://chatpost-backend
    depends_on:
      - backend
      - db
