services:
  frontend:
    image: chatpost
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5200:5200"
    command: serve -s ./dist -p 5200
    depends_on:
      - backend
  backend:
    image: chatpost
    ports:
      - "3200:3200"
    command: node ./dist-ssr/index.js
