services:
  db:
    image: postgres:16-alpine
    hostname: chatpost-db
    restart: always
    ports:
      - "8102:5432" # 単体起動時はホストPCから 8102 でアクセス可
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: chatpost
    hostname: chatpost-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8101:8101"
    command: node ./dist-ssr/index.js
    environment:
      - VITE_BACKEND_URL=http://chatpost-backend
      - VITE_DB_URL=postgres://postgres:postgres@chatpost-db:5432/chatpost
    depends_on:
      - db
  frontend:
    image: chatpost
    restart: always
    ports:
      - "8100:8100"
    command: sh -c "cd ./dist && http-server -p 8100"
    environment:
      - VITE_BACKEND_URL=http://chatpost-backend
    depends_on:
      - backend
      - db
